### ISSUE TITLE
python3 bug with --contents

### ISSUE THREAD

**Issue by wdoekes** [ossobv/sipzamine#10]
Cannot print --contents in py3.
```
Traceback (most recent call last):
  File "/usr/local/bin/sipzamine", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/sipzamine/__main__.py", line 232, in main
    show_contents=args.contents)
  File "/usr/local/lib/python3.5/dist-packages/sipzamine/sipzamine.py", line 121, in main
    print_dialog(dialog, packet_highlights, show_contents=show_contents)
  File "/usr/local/lib/python3.5/dist-packages/sipzamine/sipzamine.py", line 105, in print_dialog
    print(data_munge.sub('  ', packet.data))
TypeError: cannot use a string pattern on a bytes-like object
```
py3 (only) fix:
```
        if show_contents:
            print(data_munge.sub('  ', packet.data.decode('utf-8', 'replace')))
```

**Comment by wdoekes** [comment]
Fixed in v0.5
